# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bulade_donor_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  flyway: # org.flywaydb.core.internal.configuration.models.FlywayModel
    enable: true
    ## 迁移sql脚本文件存放路径，默认db/migration,db/aaa,classpath:db/migration,
    locations: filesystem:database/migration
#    # 设置为true，当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true

donor:
  security:
    token-header: Authorization
    token-secret: abcdefghijklmnopqrstuvwxyz
    token-timeout: 1d
    session-timeout: 30m
    mock-enable: true
    mock-secret: test
    permit-all_urls:
      - /api/admin/login #不需要登录

jwt:
  signing.key: nEuBwbvzrXzKmijgDvmbSx8ODyw5PGRJ0vj64t+LWzA=
