springdoc:
  server-urls:
    - http://127.0.0.1:9090
  swagger-ui:
    enabled: true
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /swagger-ui/api-docs
