springdoc:
  server-urls:
    - http://127.0.0.1:48080
  swagger-ui:
    enabled: true
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh_cn

donor:
  info:
    version: 1.0.0
    base-package: com.bulade.donor
  swagger:
    title: 献血服务
    description: 提供管理后台所有功能
    version: ${donor.info.version}
