# 服务器的HTTP端口
server:
  port: 48080

# Spring配置
spring:
  application:
    name: bulade-donor
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 200
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: ImoocEcommerceHikariCP
  profiles:
    active:
      - dev
      - swagger

# MyBatis
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.bulade.**.model
  configuration:
    call-setters-on-nulls: true
    mapUnderscoreToCamelCase: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.bulade.donor.framework.mybatis.typehandler.CompositeEnumTypeHandler

# 日志配置
#logging:
#  level:
#    com.bulade.donor: debug
#    org.springframework: warn

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
