# 服务器的HTTP端口
server:
  port: 48080

# 项目相关配置
donor:
  # 名称
  name: bulade-donor
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2024


# Spring配置
spring:
  application:
    name: 献血服务
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 200
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: ImoocEcommerceHikariCP
  profiles:
    active:
      - dev
      - swagger
  # 文件上传
  servlet:
    multipart:
      max-request-size: 5MB # 单个文件大小
      max-file-size: 5MB # 设置总上传的文件大小
    # 资源信息
#    messages:
      # 国际化资源文件路径
    # basename: static/i18n/messages

# MyBatis
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.bulade.**.model
  configuration:
    call-setters-on-nulls: true
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.bulade.donor: debug
    org.springframework: warn

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30


